### ISSUE TITLE
Can you drop on crates.io an invite on me so I can publish the crate, David? thx

### ISSUE THREAD

**Issue by przygienda** [slog-rs/kvfilter#6]

**Comment by dpc** [comment]
I've already added you to owners. You should be able to publish new version.

**Comment by przygienda** [comment]
prz-mbp:kvfilter prz$ cargo publish --allow-dirty
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Packaging slog-kvfilter v0.4.1 (file:///gitlab/kvfilter)
   Verifying slog-kvfilter v0.4.1 (file:///gitlab/kvfilter)
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling slog v2.0.12
   Compiling slog-kvfilter v0.4.1 (file:///gitlab/kvfilter/target/package/slog-kvfilter-0.4.1)
    Finished dev [unoptimized + debuginfo] target(s) in 4.61 secs
   Uploading slog-kvfilter v0.4.1 (file:///gitlab/kvfilter)
error: api errors: this crate exists but you don't seem to be an owner. If you believe this is a mistake, perhaps you need to accept an invitation to be an owner before publishing.

**Comment by przygienda** [comment]
alternately, I merged into master and tagged 0.4.1 you can just checkout 98ca7cc1637b7c6c57213cf9fe77d1b8a2b3a6d4 and publish

**Comment by dpc** [comment]
@przygienda 
```
[I] dpc@futex ~/l/r/s/json (master)> cargo owner --add  przygienda
    Updating registry `https://github.com/rust-lang/crates.io-index`            
       Owner user przygienda has been invited to be an owner of crate slog-json 
```

Again, some invite is waiting for you somewhere. :D

**Comment by przygienda** [comment]
I got an invite for slog-json ;-)

**Comment by dpc** [comment]
Oh dear. Oh well, please don't abuse it. :)

**Comment by dpc** [comment]
```
[I] dpc@futex ~/l/r/s/kvfilter ((75359d4f…))> cargo owner --add  przygienda
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to invite owners to crate kvfilter: api errors: `przygienda` is already an owner
```
